// Implemented by Gemini.
// src/app/api/genkit/[[...path]]/route.ts
// ** This configuration is primarily for Genkit's internal tooling/UI **
// ** It does NOT directly impact the serverless execution of flows **
// ** when called from your Next.js components/server actions. **

// import {genkit} from 'genkit'; // genkit instance is usually defined elsewhere (e.g., ai-instance.ts)
import {googleAI} from '@genkit-ai/googleai';
// import {defineFlow} from 'genkit'; // Flows are defined in their own files
// import {z} from 'zod';
import {configureGenkit} from '@genkit-ai/next/plugin';
// Firebase and GoogleCloud plugins are removed as Firestore is no longer used.

// Import flow definitions (adjust paths as needed)
// These imports are mainly for the Genkit developer UI to discover flows.
// They might not be strictly necessary if you only call flows directly.
import '@/ai/flows/analyze-image.ts';
import '@/ai/flows/voice-diagnosis.ts';
import '@/ai/flows/symptom-checker-flow.ts';
import '@/ai/flows/mental-health-flow.ts';
import '@/ai/flows/dietary-analysis-flow.ts';

// IMPORTANT: Make sure to configure authentication and authorization
// for your API endpoint if needed for specific Genkit UI features.
export const config = configureGenkit({
  plugins: [
    googleAI({ // For interacting with Google AI models (Gemini)
      apiKey: process.env.GOOGLE_GENAI_API_KEY, // This key MUST be set in .env
    }),
    // googleCloud(), // Removed: No longer using Google Cloud plugin for Firestore
    // firebase(), // Removed: No longer using Firebase plugin for Firestore stores
  ],
  // flowStateStore: 'firebase', // Removed: No longer using Firestore
  // traceStore: 'firebase', // Removed: No longer using Firestore
  // evaluationStore: 'firebase', // Removed: No longer using Firestore
  // Default stores (memory, file) will be used if not specified, or you can configure others.
  // For local development without persistence, these can be omitted.
  // For production, you might consider a persistent store if Genkit UI features are heavily used.
  enableTracingAndMetrics: true, // Enable tracing for observability
  // If you have enabled billing in Google Cloud, you can specify a billing account.
  // billingAccount: '12345-67890-ABCDEF',
  logLevel: 'debug', // Set log level (debug, info, warn, error)
  promptDir: './src/ai/prompts', // Directory for prompt templates (if any)
});

// The route handler is automatically generated by configureGenkit
export {GET, POST} from '@genkit-ai/next';
